<?php

namespace Database\Seeders;

use App\Models\LaporanKerja;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LaporanKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $laporanTotok = [
            ['nomor_spt'=>'094/1214/2024','tanggal_spt'=>'01-12-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT Tasindo Dharma Industri','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1214/2024','tanggal_spt'=>'01-12-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Jamafac','tk'=>'','wlkp'=> 1,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1214/2024','tanggal_spt'=>'01-12-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Hutan Makmur Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1214/2024','tanggal_spt'=>'01-12-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Bank Central Asia Cab. Kendal','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1214/2024','tanggal_spt'=>'01-12-2024','jenis_anggaran'=>'','nama_perusahaan'=>'SPBU 44.513.23','tk'=>'','wlkp'=> 1,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/980/2024','tanggal_spt'=>'02-07-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Utama Core Albasia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 1,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/980/2024','tanggal_spt'=>'02-07-2024','jenis_anggaran'=>'','nama_perusahaan'=>'Koperasi Jateng Amanah','tk'=>'','wlkp'=> 1,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/980/2024','tanggal_spt'=>'02-07-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Tirta Sukses Perkasa','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/980/2024','tanggal_spt'=>'02-07-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Kembangarum Indah Perkasa','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/980/2024','tanggal_spt'=>'02-07-2024','jenis_anggaran'=>'','nama_perusahaan'=>'Pondok Modern Yayasan Selamat','tk'=>'','wlkp'=> 1,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/463/2024','tanggal_spt'=>'03-04-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Tri Sinar Purnama','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/378/2024','tanggal_spt'=>'03/29/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. BPR Artha Kaliwungu','tk'=>'','wlkp'=> 1,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 1,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/570/2024','tanggal_spt'=>'03-07-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT Mas Arya Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2266/2024','tanggal_spt'=>'04/17/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. U-Winfly Indonesia Industries','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 1,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1107/2024','tanggal_spt'=>'04/22/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Prima Duta Sejati','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/918/2024','tanggal_spt'=>'04/21/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Sukasari Mitra Mandiri','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1067/2024','tanggal_spt'=>'04/23/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Borine Technology Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1001/2024','tanggal_spt'=>'04/22/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Central Pertiwi Bahari','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1326/2024','tanggal_spt'=>'05/08/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Polaris Uno Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1326/2024','tanggal_spt'=>'05/08/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Boga Makmur Gracia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1326/2024','tanggal_spt'=>'05-08-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Adventa Biotech International','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1 ,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1326/2024','tanggal_spt'=>'05-08-2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Alnu Sporting Goods','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1326/2024','tanggal_spt'=>'05-08-2024','jenis_anggaran'=>'','nama_perusahaan'=>'RS. Charlie Hospital','tk'=>'','wlkp'=> 0,'wkwi'=> 1,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 1,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/63/2024','tanggal_spt'=>'06/24/2024','jenis_anggaran'=>'','nama_perusahaan'=>'Dealer Yamaha Yudhistira','tk'=>'','wlkp'=> 1,'wkwi'=> 1,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 1,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/63/2024','tanggal_spt'=>'06/24/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. BPR Kendali Artha','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/63/2024','tanggal_spt'=>'06/24/2024','jenis_anggaran'=>'','nama_perusahaan'=>'Hotel Grand Anugerah','tk'=>'','wlkp'=> 1,'wkwi'=> 1,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/63/2024','tanggal_spt'=>'06/24/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Federal International Finance Pamularsih','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/63/2024','tanggal_spt'=>'06/24/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Polygorup Manufaktur Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/69/2024','tanggal_spt'=>'07/09/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Matahari Tire Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/69/2024','tanggal_spt'=>'07/09/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Longhi Technology Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/69/2024','tanggal_spt'=>'07/09/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Kencana Sukses Gemilang','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/93/2024','tanggal_spt'=>'08/06/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Dharmasrana Rahardja','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/93/2024','tanggal_spt'=>'08/06/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Summit Oto Finance','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/93/2024','tanggal_spt'=>'08/06/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Bussan Auto Finance','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2610/2024','tanggal_spt'=>'09/02/2024','jenis_anggaran'=>'','nama_perusahaan'=>'Agrowisata Taman Tirto Arum','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2610/2024','tanggal_spt'=>'09/02/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. BPR Anugerah Harta','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 1,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2610/2024','tanggal_spt'=>'09/02/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. APM Auto Components Indonesia','tk'=>'','wlkp'=> 1,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2610/2024','tanggal_spt'=>'09/02/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Alba Tridi Plastics Recyling Indonesia','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 1,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1166/2024','tanggal_spt'=>'','jenis_anggaran'=>'','nama_perusahaan'=>'','tk'=>'PT. Xin Liang Indonesia','wlkp'=> 1,'wkwi'=> 1,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 1,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/236/2024','tanggal_spt'=>'02/20/2024','jenis_anggaran'=>'','nama_perusahaan'=>'CV Rahma Abadi','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2403/2024','tanggal_spt'=>'04/26/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Care Guard','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 1,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/1687/2024','tanggal_spt'=>'06/05/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Sentinel Cakra Buana','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/70/2024','tanggal_spt'=>'07/09/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Optima Sinergi Comvestama','tk'=>'','wlkp'=> 0,'wkwi'=> 0,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 0,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
            ['nomor_spt'=>'094/2576/2024','tanggal_spt'=>'08/26/2024','jenis_anggaran'=>'','nama_perusahaan'=>'PT. Bakti Pratama','tk'=>'','wlkp'=> 1,'wkwi'=> 1,'tka'=> 0,'kompensasi'=> 0,'tki'=> 0,'ump'=> 0,'lembur'=> 0,'thr'=> 0,'cutith'=> 0,'cutihamil'=> 0,'pkb'=> 1,'susu'=> 0,'jamsos'=> 0,'k3'=> 0,'lainnya'=>'','keterangan'=>'','tanggal_np_I'=>'','no_np_I'=>'','tanggal_np_II'=>'','no_np_II'=>'','tanggal_tmp2t'=>'','no_tmp2t'=>''],
        ];

        foreach($laporanTotok as $each){
            $tanggal = $each['tanggal_spt'];
            LaporanKerja::create([
                'nip' => '198403262010011018',
                'nomor_spt' => $each['nomor_spt'],
                'tanggal_spt' => Carbon::parse($tanggal),
                'jenis_anggaran' => 'Rencana Kerja (Non Anggaran)',
                'nama_perusahaan' => $each['nama_perusahaan'],
                'tk' => 100,
                'wlkp' => $each['wlkp'],
                'wkwi' => $each['wkwi'],
                'tka'=> $each['tka'],
                'kompensasi'=> $each['kompensasi'],
                'tki'=> $each['tki'],
                'ump'=> $each['ump'],
                'lembur'=> $each['lembur'],
                'thr'=> $each['thr'],
                'cutith'=> $each['cutith'],
                'cutihamil'=> $each['cutihamil'],
                'pkb'=> $each['pkb'],
                'susu'=> $each['susu'],
                'jamsos'=> $each['jamsos'],
                'k3'=> $each['k3'],
                // 'lainnya',
                // 'keterangan',
                // 'tanggal_np_I',
                // 'no_np_I',
                // 'tanggal_np_II',
                // 'no_np_II',
                // 'tanggal_tmp2t',
                // 'no_tmp2t',
            ]);
        }
    }
}
